# Server configuration
bind = "[::1]:8080" # Required
# Examples:
# "[::]:80" - listen on port 80 on all IPv4/IPv6 addresses
# "[::1]:80" - listen on port 80 on localhost
# "192.168.1.1:12345" - listen on port 12345 on a specific IPv4 address
# "unix:/run/gh-deploy/http.sock" - listen on a Unix socket

# Enable Git LFS support
# git_lfs = true

# Optional: TLS configuration
# [tls]
# cert_file = "/path/to/cert.pem" # TLS certificate file
# key_file = "/path/to/key.pem" # TLS private key file

# GitHub App configuration
[github_app]
client_id = "123456abcdefGHIJKLMN"                    # GitHub App client ID
private_key_file = "/etc/gh-deploy/key.pem"           # GitHub App private key file
webhook_secret_file = "/etc/gh-deploy/webhook-secret" # File with webhook secret

# Repositories and branches to deploy
[[projects]]
repository = "owner/repo"
branch = "main"           # Branch to watch for changes
path = "/var/www/repo"    # This folder should be writable by user running the gh-deploy
command = "make deploy"   # Optional: command to run after update
timeout = 300             # in seconds, default is 120
